apiVersion: apps/v1
kind: Deployment
metadata:
  name: owner-exchange
spec:
  selector:
    matchLabels:
      app: owner-exchange
  replicas: 1
  template:
    metadata:
      labels:
        app: owner-exchange
    spec:
      containers:
        - name: owner-exchange
          image: niel4265/owner-exchange:latest
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: PYTHONUNBUFFERED
              value: "True"
            - name: PYTHONIOENCODING
              value: "UTF-8"