apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: exchange_rest
spec:
  selector:
    matchLabels:
      app: exchange_rest_app
  replicas: 1
  template:
    metadata:
      labels:
        app: exchange_rest_app
    spec:
      containers:
        - name: master
          image: niel4265/exchange-rest-service:latest
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          env:
#            - name: REDIS_HOST
#              value: redis
#            - name: RABBITMQ_HOST
#              value: rabbitmq
            - name: PYTHONUNBUFFERED
              value: "True"
            - name: PYTHONIOENCODING
              value: "UTF-8"
          ports:
            - containerPort: 5000