apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-exchange
spec:
  selector:
    matchLabels:
      app: rest-exchange
  replicas: 1
  template:
    metadata:
      labels:
        app: rest-exchange
    spec:
      containers:
        - name: rest-exchange
          image: niel4265/rest-exchange:latest
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: PYTHONUNBUFFERED
              value: "True"
            - name: PYTHONIOENCODING
              value: "UTF-8"
            - name: VALID_ASSETS
              value: '["AAPL", "MSFT", "FB"]'
          ports:
            - containerPort: 5000
